baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Johanna Bayer'
theme = "anatole"
summarylength = 50
enableEmoji = true
enableRobotsTXT = true
favicon = "favicons/"

[math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "mathjax"  # options: "katex", "mathjax". default is "katex".

[params]
title = "Hi I'm Jo"
author = "Johanna Bayer"
description = "Research Fellow at the Donders Institute. <br> Machine learning, Open Science,<br> Neuroimaging, Computer Science"
profilePicture = "images/Johanna.jpg"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/johanna-bayer/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/likeajumprope"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/likeajumprope"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:johanna.m.m.bayer@gmail.com"

[menu]
 [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"


  [[menu.main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/cv/"

 [[menu.main]]
  name = "Education"
  weight = 310
  identifier = "cv_education"
  url = "/cv_education/"
  parent = "cv"


  [[menu.main]]
  name = "Conferences/Talks"
  weight = 320
  identifier = "conferences"
  url = "/conferences/"
  parent = "cv"

  [[menu.main]]
  name = "Publications"
  weight = 200
  identifier = "publications"
  url = "/publications/"

  [[menu.main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "Presentations"
  weight = 200
  identifier = "presentations"
  url = "/presentations/"


#[[menu.main]]
# name = "Projects"
# weight = 200
#  identifier = "projects"
#  url = "/projects/"

#[[menu.main]]
  #name = "Book reviews"
  #weight = 300
  #identifier = "books"
  #url = "/books/"