baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Johanna Bayer'
theme = "anatole"
summarylength = 50
enableEmoji = true
enableRobotsTXT = true

[math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "mathjax"  # options: "katex", "mathjax". default is "katex".

[params]
title = "Hi I'm Jo"
author = "Johanna Bayer"
description = "Research Fellow at the University of Melbourne. <br> Machine learning, Open Science,<br> Neuroimaging, Computer Science"
profilePicture = "images/Johanna.jpg"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/likeajumprope"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/likeajumprope"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:bayerj@student.unimelb.edu.au"

[menu]
 [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"

[[menu.main]]
  name = "Curriculum Vitae"
  weight = 200
  identifier = "CV"
  url = "/CV/"

[[menu.main]]
  name = "Publications"
  weight = 200
  identifier = "Publications"
  url = "/Publications/"

 [[menu.main]]
  name = "portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"