baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
<<<<<<< HEAD
title = "Johanna's Website"
=======
title = "Website of Jane Doe"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
>>>>>>> 62ea796e3718964fbe38748845e6f8e059fc1df5
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
